### ISSUE TITLE
Checklist for 1.0 release

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidon-eager#29]
- [x] Bump to nf-core/eager 2.5.*, to use mapDamage with a read limit for damage calculation.
- [x] Remove template files that have been transferred to minotaur-recipes.
- [x] Remove `packages/` directory (moved to minotaur-recipes repo.
